# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accbehonuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, db_column='UserID', null=True)),
                ('accbehid', models.IntegerField(blank=True, db_column='AccBehID', null=True)),
            ],
            options={
                'db_table': 'accbehonuser',
            },
        ),
        migrations.CreateModel(
            name='AccDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(db_column='AccLanguage')),
                ('description', models.TextField(blank=True, db_column='AccDescription', null=True)),
                ('updatedtime', models.DateTimeField(db_column='AccUpdatedTime')),
            ],
            options={
                'db_table': 'acc_description',
            },
        ),
        migrations.CreateModel(
            name='Accommodatie',
            fields=[
                ('accid', models.AutoField(db_column='AccID', primary_key=True, serialize=False)),
                ('type', models.IntegerField(db_column='AccType')),
                ('address', models.CharField(blank=True, db_column='AccAddress', max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='AccZip', max_length=10, null=True)),
                ('city', models.CharField(blank=True, db_column='AccPlace', max_length=50, null=True)),
                ('country', models.IntegerField(db_column='AccCountry')),
                ('district', models.IntegerField(db_column='AccDistrict')),
                ('rooms', models.IntegerField(db_column='AccNmbRooms')),
                ('places', models.IntegerField(db_column='AccNmbSPlac')),
                ('homepage', models.CharField(blank=True, db_column='AccHomepage', max_length=200, null=True)),
                ('vz1', models.BooleanField(db_column='Acc_vz1')),
                ('vz2', models.BooleanField(db_column='Acc_vz2')),
                ('vz3', models.BooleanField(db_column='Acc_vz3')),
                ('vz4', models.BooleanField(db_column='Acc_vz4')),
                ('vz5', models.BooleanField(db_column='Acc_vz5')),
                ('vz6', models.BooleanField(db_column='Acc_vz6')),
                ('vz7', models.BooleanField(db_column='Acc_vz7')),
                ('vz8', models.BooleanField(db_column='Acc_vz8')),
                ('picturefront', models.IntegerField(blank=True, db_column='Acc_PictureFront', null=True)),
                ('acc_intro', models.TextField(blank=True, db_column='Acc_Intro', null=True)),
                ('acc_intro_nl', models.TextField(blank=True, db_column='Acc_Intro_NL', null=True)),
                ('acc_intro_de', models.TextField(blank=True, db_column='Acc_Intro_DE', null=True)),
                ('acc_intro_fr', models.TextField(blank=True, db_column='Acc_Intro_FR', null=True)),
                ('status', models.BooleanField()),
                ('datumtoegevoegd', models.DateTimeField(db_column='DatumToegevoegd')),
                ('datumgewijzigd', models.DateTimeField(blank=True, db_column='DatumGewijzigd', null=True)),
                ('datumonline', models.DateTimeField(db_column='DatumOnline')),
                ('sort', models.IntegerField(db_column='AccSort')),
                ('gebruikreserveringen', models.BooleanField(db_column='GebruikReserveringen')),
                ('publicreserveringen', models.BooleanField(db_column='PublicReserveringen')),
                ('aantaldagen', models.IntegerField(blank=True, db_column='AantalDagen', null=True)),
                ('accaddsort', models.IntegerField(blank=True, db_column='AccAddSort', null=True)),
                ('verkoopprijs', models.CharField(blank=True, max_length=15, null=True)),
                ('ground', models.CharField(blank=True, max_length=10, null=True)),
                ('bground', models.CharField(blank=True, max_length=10, null=True)),
                ('cdate', models.CharField(blank=True, max_length=10, null=True)),
                ('teller1', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accommodatie',
                'verbose_name': 'accommodation',
                'verbose_name_plural': 'accommodations',
            },
        ),
        migrations.CreateModel(
            name='AccommodatieBeheerder',
            fields=[
                ('accbehid', models.AutoField(db_column='AccBehID', primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=50)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=100, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=10, null=True)),
                ('city', models.CharField(blank=True, db_column='Place', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=20, null=True)),
                ('telephone', models.CharField(blank=True, db_column='Telephone', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, db_column='MobPhone', max_length=20, null=True)),
                ('datumgeregistreerd', models.DateTimeField(db_column='DatumGeregistreerd')),
                ('datumgewijzigd', models.DateTimeField(blank=True, db_column='DatumGewijzigd', null=True)),
                ('contact_en', models.NullBooleanField(db_column='Contact_EN')),
                ('contact_nl', models.NullBooleanField(db_column='Contact_NL')),
                ('contact_de', models.NullBooleanField(db_column='Contact_DE')),
                ('contact_fr', models.NullBooleanField(db_column='Contact_FR')),
            ],
            options={
                'db_table': 'accommodatie_beheerder',
            },
        ),
        migrations.CreateModel(
            name='AccommodatiePictures',
            fields=[
                ('pictureid', models.AutoField(db_column='PictureID', primary_key=True, serialize=False)),
                ('picturetext', models.CharField(blank=True, db_column='PictureText', max_length=100, null=True)),
                ('picturetext_nl', models.CharField(blank=True, db_column='PictureText_NL', max_length=100, null=True)),
                ('picturetext_de', models.CharField(blank=True, db_column='PictureText_DE', max_length=100, null=True)),
                ('picturetext_fr', models.CharField(blank=True, db_column='PictureText_FR', max_length=100, null=True)),
                ('pictureext', models.CharField(db_column='PictureExt', max_length=4)),
                ('pictureaccid', models.IntegerField(blank=True, db_column='PictureAccID', null=True)),
                ('accommodatie', models.ForeignKey(db_column='AccID', on_delete=django.db.models.deletion.CASCADE, to='hplan_app.Accommodatie')),
                ('beheerder', models.ForeignKey(blank=True, db_column='AccBehID', null=True, on_delete=django.db.models.deletion.CASCADE, to='hplan_app.AccommodatieBeheerder')),
            ],
            options={
                'db_table': 'accommodatie_pictures',
            },
        ),
        migrations.CreateModel(
            name='RegionLinks',
            fields=[
                ('linkid', models.AutoField(db_column='LinkID', primary_key=True, serialize=False)),
                ('countryid', models.IntegerField(blank=True, db_column='CountryID', null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='RegionID', null=True)),
                ('languageid', models.IntegerField(blank=True, db_column='LanguageID', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=200, null=True)),
                ('clicks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_links',
            },
        ),
        migrations.CreateModel(
            name='RegionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryid', models.IntegerField(blank=True, db_column='CountryID', null=True)),
                ('regionid', models.IntegerField(blank=True, db_column='RegionID', null=True)),
                ('languageid', models.IntegerField(blank=True, db_column='LanguageID', null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_text',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='UserName', max_length=25, null=True)),
                ('password', models.CharField(blank=True, db_column='UserPassword', max_length=20, null=True)),
                ('emailadres', models.CharField(blank=True, db_column='Emailadres', max_length=160, null=True)),
                ('active', models.NullBooleanField(db_column='Active')),
                ('activatiecode', models.CharField(blank=True, max_length=8, null=True)),
                ('lastlogin', models.DateTimeField(blank=True, db_column='LastLogin', null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='accommodatie',
            name='beheerder',
            field=models.ForeignKey(blank=True, db_column='AccBehID', null=True, on_delete=django.db.models.deletion.CASCADE, to='hplan_app.AccommodatieBeheerder'),
        ),
        migrations.AddField(
            model_name='accdescription',
            name='accommodatie',
            field=models.ForeignKey(db_column='AccID', on_delete=django.db.models.deletion.CASCADE, to='hplan_app.Accommodatie'),
        ),
    ]
