# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:40
from __future__ import unicode_literals

from django.db import migrations

def link_districts(apps, schema_editor):
    Accommodatie = apps.get_model('hplan_app', 'Accommodatie')
    District = apps.get_model('hplan_app', 'District')
    for acc in Accommodatie.objects.all():
        try:
            print acc.country.id, acc.district
            district = District.objects.get(country_id=acc.country.id, districtid=acc.district)
            print district.id
            acc.district_fk = district
            acc.save()
        except:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0004_accommodatie_district_fk'),
    ]

    operations = [
        migrations.RunPython(link_districts),
    ]
