# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0006_remove_accommodatie_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodatie',
            old_name='district_fk',
            new_name='district',
        ),
    ]
