# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0007_auto_20160728_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accdescription',
            options={'verbose_name': 'accommodation description', 'verbose_name_plural': 'accommodation descriptions'},
        ),
        migrations.AlterUniqueTogether(
            name='accdescription',
            unique_together=set([('accommodatie', 'language')]),
        ),
    ]
