# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0008_auto_20160804_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.IntegerField(unique=True)),
                ('language', models.CharField(max_length=25, unique=True, verbose_name='language')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
            },
        ),
        migrations.AlterField(
            model_name='accdescription',
            name='description',
            field=models.TextField(blank=True, db_column='AccDescription', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='accdescription',
            name='updatedtime',
            field=models.DateTimeField(db_column='AccUpdatedTime', verbose_name='date last changed'),
        ),
        migrations.AlterField(
            model_name='district',
            name='districtid',
            field=models.IntegerField(verbose_name='district id'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
    ]
