# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0009_auto_20160804_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='accdescription',
            name='language_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hplan_app.Language'),
        ),
    ]
