# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:08
from __future__ import unicode_literals

from django.db import migrations

def link_languages(apps, schema_editor):
    AccDescription = apps.get_model('hplan_app', 'AccDescription')
    Language = apps.get_model('hplan_app', 'Language')
    for acc_descr in AccDescription.objects.all():
        try:
            language = Language.objects.get(language_id=acc_descr.language)
            acc_descr.language_fk = language
            acc_descr.save()
        except:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0010_accdescription_language_fk'),
    ]

    operations = [
        migrations.RunPython(link_languages),
    ]
