# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0012_auto_20160804_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accdescription',
            old_name='language_fk',
            new_name='language',
        ),
        migrations.AlterUniqueTogether(
            name='accdescription',
            unique_together=set([('accommodatie', 'language')]),
        ),
    ]
