# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0013_auto_20160804_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodatiepictures',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='/pictures', verbose_name='picture'),
        ),
    ]
