# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0014_accommodatiepictures_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodatieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25, unique=True, verbose_name='type')),
            ],
            options={
                'verbose_name': 'accommodation type',
                'verbose_name_plural': 'accommodation types',
            },
        ),
    ]
