# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hplan_app', '0015_accommodatietype'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodatie',
            name='type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hplan_app.AccommodatieType', verbose_name='type'),
        ),
    ]
